#!/bin/bash
set -e

echo "ℹ️  Release Process Information"
echo ""
echo "This repository uses AUTOMATED releases on every merge to main."
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📋 How it works:"
echo ""
echo "  1. Create a PR with conventional commits:"
echo "     • feat: New feature (bumps minor version)"
echo "     • fix: Bug fix (bumps patch version)"
echo "     • BREAKING CHANGE: Breaking change (bumps major version)"
echo ""
echo "  2. Merge PR to main"
echo ""
echo "  3. GitHub Actions automatically:"
echo "     ✅ Analyzes commits since last release"
echo "     ✅ Bumps version using standard-version"
echo "     ✅ Updates CHANGELOG.md"
echo "     ✅ Runs tests and builds"
echo "     ✅ Publishes to npm with provenance"
echo "     ✅ Creates GitHub release with changelog"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "💡 Tips:"
echo ""
echo "  • Use conventional commit format in PR titles"
echo "  • Version bumps are automatic based on commit types"
echo "  • Every merge to main triggers a release"
echo "  • Check the 'Release and Publish' workflow status after merge"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🔗 Resources:"
echo ""
echo "  • Conventional Commits: https://www.conventionalcommits.org"
echo "  • Workflow: .github/workflows/publish-npm.yml"
echo "  • Latest releases: https://github.com/codewizwit/human-in-the-loop/releases"
echo "  • npm package: https://www.npmjs.com/package/@human-in-the-loop/cli"
echo ""
