name: Update Repository Tree
description: Regenerate repository structure tree in README.md

runs:
  using: composite
  steps:
    - name: Generate tree structure
      shell: bash
      run: |
        echo "Generating repository tree..."
        pnpm tree > /tmp/tree-output.txt

    - name: Update README with tree
      shell: bash
      run: |
        # Extract tree content (everything after the header line)
        TREE_CONTENT=$(tail -n +2 /tmp/tree-output.txt)

        # Create temp file with updated README
        awk -v tree="$TREE_CONTENT" '
          BEGIN { in_tree = 0 }
          /^## 📂 Repository Structure/ { print; getline; print; in_tree = 1; print "```"; print tree; next }
          /^```$/ && in_tree { in_tree = 0; next }
          !in_tree { print }
        ' README.md > /tmp/readme-updated.md

        # Replace original if different
        if ! diff -q README.md /tmp/readme-updated.md > /dev/null 2>&1; then
          mv /tmp/readme-updated.md README.md
          echo "✅ README.md tree updated"
        else
          echo "✅ Tree is already up to date"
        fi
