import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import { parse as parseYaml } from 'yaml';
import { resolvePath } from './file-operations';

/**
 * Interface for prompt YAML structure
 */
interface PromptYaml {
  id: string;
  name: string;
  description: string;
  template: string;
  variables?: Array<{
    name: string;
    description: string;
    required: boolean;
  }>;
}

/**
 * Creates a Claude Code slash command from a prompt template
 * @param promptPath - Path to the prompt.yaml file
 * @param commandName - Name for the slash command (defaults to prompt id)
 * @returns Path to the created command file
 */
export function createClaudeCommand(
  promptPath: string,
  commandName?: string
): string {
  // Read and parse the prompt.yaml file
  const yamlContent = readFileSync(promptPath, 'utf-8');
  const prompt = parseYaml(yamlContent) as PromptYaml;

  // Use provided command name or default to prompt id
  const cmdName = commandName || prompt.id;

  // Determine .claude/commands directory
  const homeDir = process.env.HOME || process.env.USERPROFILE || '~';
  const claudeDir = resolvePath(join(homeDir, '.claude'));
  const commandsDir = join(claudeDir, 'commands');

  // Create directories if they don't exist
  if (!existsSync(claudeDir)) {
    mkdirSync(claudeDir, { recursive: true });
  }
  if (!existsSync(commandsDir)) {
    mkdirSync(commandsDir, { recursive: true });
  }

  // Generate the command file content
  const commandContent = generateCommandContent(prompt);

  // Write the command file
  const commandFilePath = join(commandsDir, `${cmdName}.md`);
  writeFileSync(commandFilePath, commandContent, 'utf-8');

  return commandFilePath;
}

/**
 * Generates the markdown content for a Claude Code command
 * @param prompt - The parsed prompt YAML
 * @returns Markdown content for the command file
 */
function generateCommandContent(prompt: PromptYaml): string {
  const lines: string[] = [];

  // Add header comment
  lines.push(
    `# ${prompt.name}\n`,
    `# ${prompt.description}\n`,
    `# Generated by Human in the Loop CLI\n`
  );

  // Add variable instructions if present
  if (prompt.variables && prompt.variables.length > 0) {
    lines.push(`# Variables:`);
    for (const variable of prompt.variables) {
      const required = variable.required ? '(required)' : '(optional)';
      lines.push(
        `#   {{${variable.name}}} ${required} - ${variable.description}`
      );
    }
    lines.push('');
  }

  // Add the template content
  lines.push(prompt.template);

  return lines.join('\n');
}

/**
 * Checks if Claude Code integration is available
 * @returns true if .claude directory exists or can be created
 */
export function isClaudeAvailable(): boolean {
  try {
    const homeDir = process.env.HOME || process.env.USERPROFILE;
    if (!homeDir) {
      return false;
    }

    const claudeDir = join(homeDir, '.claude');

    // Check if it exists or can be created
    if (existsSync(claudeDir)) {
      return true;
    }

    // Try to create it
    mkdirSync(claudeDir, { recursive: true });
    return true;
  } catch {
    return false;
  }
}
