import {
  describe,
  it,
  expect,
  beforeEach,
  afterEach,
  jest,
} from '@jest/globals';
import {
  createClaudeCommand,
  isClaudeAvailable,
  installSkillFile,
} from '../claude-integration';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

jest.mock('fs');
jest.mock('../file-operations', () => ({
  resolvePath: (path: string): string => path,
}));

const mockReadFileSync = readFileSync as jest.MockedFunction<
  typeof readFileSync
>;
const mockWriteFileSync = writeFileSync as jest.MockedFunction<
  typeof writeFileSync
>;
const mockMkdirSync = mkdirSync as jest.MockedFunction<typeof mkdirSync>;
const mockExistsSync = existsSync as jest.MockedFunction<typeof existsSync>;

describe('claude-integration', () => {
  const homeDir = '/home/user';
  const originalEnv = process.env;

  beforeEach(() => {
    jest.clearAllMocks();
    process.env = { ...originalEnv, HOME: homeDir };
  });

  afterEach(() => {
    process.env = originalEnv;
  });

  describe('createClaudeCommand', () => {
    describe('with XML files', () => {
      it('should create command from pure XML format', () => {
        const xmlContent = `<prompt>
  <metadata>
    <id>test-prompt</id>
    <name>Test Prompt</name>
    <description>A test prompt</description>
    <version>1.0.0</version>
    <category>testing</category>
  </metadata>

  <examples>
    <example>
      <description>Test example</description>
    </example>
  </examples>

  <context>
You are a test expert.
  </context>

  <instructions>
Test template content
  </instructions>

  <constraints>
- Follow best practices
  </constraints>

  <output_format>
Provide structured output
  </output_format>
</prompt>`;

        mockReadFileSync.mockReturnValue(xmlContent);
        mockExistsSync.mockReturnValue(true);

        const result = createClaudeCommand('/path/to/prompt.xml');

        expect(mockWriteFileSync).toHaveBeenCalledWith(
          join(homeDir, '.claude', 'commands', 'test-prompt.md'),
          expect.stringContaining('# Test Prompt'),
          'utf-8'
        );
        expect(mockWriteFileSync).toHaveBeenCalledWith(
          expect.any(String),
          expect.stringContaining('# A test prompt'),
          'utf-8'
        );
        expect(mockWriteFileSync).toHaveBeenCalledWith(
          expect.any(String),
          expect.stringContaining('# Generated by Human in the Loop CLI'),
          'utf-8'
        );
        expect(mockWriteFileSync).toHaveBeenCalledWith(
          expect.any(String),
          expect.stringContaining('<context>'),
          'utf-8'
        );
        expect(mockWriteFileSync).toHaveBeenCalledWith(
          expect.any(String),
          expect.stringContaining('<instructions>'),
          'utf-8'
        );
        expect(mockWriteFileSync).toHaveBeenCalledWith(
          expect.any(String),
          expect.not.stringContaining('<metadata>'),
          'utf-8'
        );
        expect(mockWriteFileSync).toHaveBeenCalledWith(
          expect.any(String),
          expect.not.stringContaining('<examples>'),
          'utf-8'
        );
        expect(result).toBe(
          join(homeDir, '.claude', 'commands', 'test-prompt.md')
        );
      });

      it('should handle XML with variables', () => {
        const xmlContent = `<prompt>
  <metadata>
    <id>xml-vars</id>
    <name>XML Variables</name>
    <description>Prompt with variables</description>
    <variables>
      <variable>
        <name>input</name>
        <description>Test input</description>
        <required>true</required>
      </variable>
    </variables>
  </metadata>

  <instructions>
Template with {{input}}
  </instructions>
</prompt>`;

        mockReadFileSync.mockReturnValue(xmlContent);
        mockExistsSync.mockReturnValue(true);

        createClaudeCommand('/path/to/prompt.xml');

        expect(mockWriteFileSync).toHaveBeenCalledWith(
          expect.any(String),
          expect.stringContaining('{{input}} (required) - Test input'),
          'utf-8'
        );
      });

      it('should throw error for XML without metadata', () => {
        const invalidXml = `<prompt>
  <instructions>
    Some instructions
  </instructions>
</prompt>`;

        mockReadFileSync.mockReturnValue(invalidXml);
        mockExistsSync.mockReturnValue(true);

        const result = createClaudeCommand('/path/to/prompt.xml');

        expect(result).toBe(join(homeDir, '.claude', 'commands', 'unknown.md'));
        expect(mockWriteFileSync).toHaveBeenCalledWith(
          expect.any(String),
          expect.stringContaining('Unknown Prompt'),
          'utf-8'
        );
      });
    });

    describe('with markdown files', () => {
      it('should create command from markdown with frontmatter', () => {
        const markdownContent = `---
id: test-prompt
name: Test Prompt
description: A test prompt
variables:
  - name: input
    description: Test input
    required: true
---

<instructions>
Test template content
</instructions>`;

        mockReadFileSync.mockReturnValue(markdownContent);
        mockExistsSync.mockReturnValue(true);

        const result = createClaudeCommand('/path/to/prompt.md');

        expect(mockWriteFileSync).toHaveBeenCalledWith(
          join(homeDir, '.claude', 'commands', 'test-prompt.md'),
          expect.stringContaining('# Test Prompt'),
          'utf-8'
        );
        expect(mockWriteFileSync).toHaveBeenCalledWith(
          expect.any(String),
          expect.stringContaining('# A test prompt'),
          'utf-8'
        );
        expect(mockWriteFileSync).toHaveBeenCalledWith(
          expect.any(String),
          expect.stringContaining('# Generated by Human in the Loop CLI'),
          'utf-8'
        );
        expect(mockWriteFileSync).toHaveBeenCalledWith(
          expect.any(String),
          expect.stringContaining('{{input}} (required) - Test input'),
          'utf-8'
        );
        expect(mockWriteFileSync).toHaveBeenCalledWith(
          expect.any(String),
          expect.stringContaining('Test template content'),
          'utf-8'
        );
        expect(result).toBe(
          join(homeDir, '.claude', 'commands', 'test-prompt.md')
        );
      });

      it('should handle markdown without variables', () => {
        const markdownContent = `---
id: simple-prompt
name: Simple Prompt
description: A simple prompt
---

Simple template`;

        mockReadFileSync.mockReturnValue(markdownContent);
        mockExistsSync.mockReturnValue(true);

        createClaudeCommand('/path/to/prompt.md');

        expect(mockWriteFileSync).toHaveBeenCalledWith(
          expect.any(String),
          expect.not.stringContaining('# Variables:'),
          'utf-8'
        );
      });

      it('should handle optional variables', () => {
        const markdownContent = `---
id: optional-vars
name: Optional Variables
description: Prompt with optional vars
variables:
  - name: optionalInput
    description: Optional input
    required: false
---

Template with optional var`;

        mockReadFileSync.mockReturnValue(markdownContent);
        mockExistsSync.mockReturnValue(true);

        createClaudeCommand('/path/to/prompt.md');

        expect(mockWriteFileSync).toHaveBeenCalledWith(
          expect.any(String),
          expect.stringContaining('{{optionalInput}} (optional)'),
          'utf-8'
        );
      });

      it('should use custom command name if provided', () => {
        const markdownContent = `---
id: test-prompt
name: Test Prompt
description: A test prompt
---

Template content`;

        mockReadFileSync.mockReturnValue(markdownContent);
        mockExistsSync.mockReturnValue(true);

        const result = createClaudeCommand('/path/to/prompt.md', 'custom-name');

        expect(result).toBe(
          join(homeDir, '.claude', 'commands', 'custom-name.md')
        );
      });

      it('should throw error for invalid frontmatter', () => {
        const invalidMarkdown = `---
invalid yaml: [
---

Content`;

        mockReadFileSync.mockReturnValue(invalidMarkdown);
        mockExistsSync.mockReturnValue(true);

        expect(() => createClaudeCommand('/path/to/prompt.md')).toThrow(
          'Invalid markdown frontmatter'
        );
      });

      it('should throw error for missing frontmatter', () => {
        const noFrontmatter = 'Just plain content without frontmatter';

        mockReadFileSync.mockReturnValue(noFrontmatter);
        mockExistsSync.mockReturnValue(true);

        expect(() => createClaudeCommand('/path/to/prompt.md')).toThrow(
          'Invalid markdown frontmatter'
        );
      });

      it('should handle variables without description', () => {
        const markdownContent = `---
id: no-desc-vars
name: No Description Variables
variables:
  - name: varWithoutDesc
    required: true
---

Template`;

        mockReadFileSync.mockReturnValue(markdownContent);
        mockExistsSync.mockReturnValue(true);

        createClaudeCommand('/path/to/prompt.md');

        expect(mockWriteFileSync).toHaveBeenCalledWith(
          expect.any(String),
          expect.stringContaining('{{varWithoutDesc}} (required) -'),
          'utf-8'
        );
      });
    });

    describe('directory creation', () => {
      it('should create .claude directory if it does not exist', () => {
        const markdownContent = `---
id: test
name: Test
---
Content`;

        mockReadFileSync.mockReturnValue(markdownContent);
        mockExistsSync.mockReturnValueOnce(false);
        mockExistsSync.mockReturnValueOnce(false);

        createClaudeCommand('/path/to/prompt.md');

        expect(mockMkdirSync).toHaveBeenCalledWith(join(homeDir, '.claude'), {
          recursive: true,
        });
        expect(mockMkdirSync).toHaveBeenCalledWith(
          join(homeDir, '.claude', 'commands'),
          { recursive: true }
        );
      });

      it('should not create directories if they already exist', () => {
        const markdownContent = `---
id: test
name: Test
---
Content`;

        mockReadFileSync.mockReturnValue(markdownContent);
        mockExistsSync.mockReturnValue(true);

        createClaudeCommand('/path/to/prompt.md');

        expect(mockMkdirSync).not.toHaveBeenCalled();
      });

      it('should use USERPROFILE on Windows if HOME is not set', () => {
        process.env = { ...originalEnv, USERPROFILE: 'C:\\Users\\test' };
        delete process.env.HOME;

        const markdownContent = `---
id: test
name: Test
---
Content`;

        mockReadFileSync.mockReturnValue(markdownContent);
        mockExistsSync.mockReturnValue(true);

        const result = createClaudeCommand('/path/to/prompt.md');

        expect(result).toContain('C:\\Users\\test');
      });

      it('should fallback to ~ if no home directory is set', () => {
        process.env = {};

        const markdownContent = `---
id: test
name: Test
---
Content`;

        mockReadFileSync.mockReturnValue(markdownContent);
        mockExistsSync.mockReturnValue(true);

        const result = createClaudeCommand('/path/to/prompt.md');

        expect(result).toContain('~');
      });
    });
  });

  describe('isClaudeAvailable', () => {
    it('should return true if .claude directory exists', () => {
      mockExistsSync.mockReturnValue(true);

      expect(isClaudeAvailable()).toBe(true);
      expect(mockExistsSync).toHaveBeenCalledWith(join(homeDir, '.claude'));
    });

    it('should create .claude directory if it does not exist', () => {
      mockExistsSync.mockReturnValue(false);

      expect(isClaudeAvailable()).toBe(true);
      expect(mockMkdirSync).toHaveBeenCalledWith(join(homeDir, '.claude'), {
        recursive: true,
      });
    });

    it('should return false if HOME is not set', () => {
      process.env = {};

      expect(isClaudeAvailable()).toBe(false);
    });

    it('should return false if directory creation fails', () => {
      mockExistsSync.mockReturnValue(false);
      mockMkdirSync.mockImplementation(() => {
        throw new Error('Permission denied');
      });

      expect(isClaudeAvailable()).toBe(false);
    });

    it('should use USERPROFILE on Windows', () => {
      process.env = { ...originalEnv, USERPROFILE: 'C:\\Users\\test' };
      delete process.env.HOME;

      mockExistsSync.mockReturnValue(true);

      expect(isClaudeAvailable()).toBe(true);
      expect(mockExistsSync).toHaveBeenCalledWith(
        expect.stringContaining('.claude')
      );
    });
  });

  describe('installSkillFile', () => {
    it('should copy skill.md to destination path', () => {
      const skillContent = `---
name: test-skill
description: A test skill
version: 1.0.0
allowed-tools:
  - Read
---

## When to Activate
Testing scenarios.`;

      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue(skillContent);

      const result = installSkillFile(
        '/lib/skills/test-skill/skill.md',
        '/home/user/.claude/skills/test-skill.md'
      );

      expect(mockReadFileSync).toHaveBeenCalledWith(
        '/lib/skills/test-skill/skill.md',
        'utf-8'
      );
      expect(mockWriteFileSync).toHaveBeenCalledWith(
        '/home/user/.claude/skills/test-skill.md',
        skillContent,
        'utf-8'
      );
      expect(result).toBe('/home/user/.claude/skills/test-skill.md');
    });

    it('should create destination directory if it does not exist', () => {
      mockMkdirSync.mockReset();
      mockExistsSync.mockReturnValue(false);
      mockReadFileSync.mockReturnValue('skill content');

      installSkillFile(
        '/lib/skills/test/skill.md',
        '/home/user/.claude/skills/test.md'
      );

      expect(mockMkdirSync).toHaveBeenCalledWith('/home/user/.claude/skills', {
        recursive: true,
      });
    });

    it('should not create directory if it already exists', () => {
      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue('skill content');

      installSkillFile(
        '/lib/skills/test/skill.md',
        '/home/user/.claude/skills/test.md'
      );

      expect(mockMkdirSync).not.toHaveBeenCalled();
    });

    it('should return the destination file path', () => {
      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue('skill content');

      const result = installSkillFile(
        '/lib/skills/code-review/skill.md',
        '/home/user/.claude/skills/code-review.md'
      );

      expect(result).toBe('/home/user/.claude/skills/code-review.md');
    });

    it('should preserve the skill file content exactly', () => {
      const complexContent = `---
name: complex-skill
description: A complex skill with special chars & symbols
version: 2.1.0
allowed-tools:
  - Read
  - Write
  - Bash
---

## When to Activate
When working with complex patterns.

## Output Format
Use structured markdown.

### Additional Notes
- Item 1
- Item 2`;

      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue(complexContent);

      installSkillFile(
        '/lib/skills/complex/skill.md',
        '/home/user/.claude/skills/complex-skill.md'
      );

      expect(mockWriteFileSync).toHaveBeenCalledWith(
        '/home/user/.claude/skills/complex-skill.md',
        complexContent,
        'utf-8'
      );
    });
  });
});
